name    'jacksoncage-killall'
version '0.1.1'
source 'git://github.com/jacksoncage/puppet-killall'
author 'Love Nyberg'
license 'Apache Version 2.0'
summary 'Install killall command'
description 'Killall Module for Debian, Ubuntu, CentOS, RHEL, & Arch'
project_page 'http://github.com/puppetlabs/puppet-killall'